import Head from 'next/head'
import { Login } from '../components/Login'
import { useSession } from 'next-auth/client'
import { useRouter } from 'next/dist/client/router'

export default function Home() {
  const [ session ] = useSession()
  const router = useRouter()

  console.log(session)
  return (
    <div>
      <Head>
        <title>fisioPront</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        { !session ? <Login /> : router.push('/home')}
      </main>

      
    </div>
  )
}
